### ISSUE TITLE
Suggest to loosen the dependency on pytube

### ISSUE THREAD

**Issue by Agnes-U** [TheHolyTachanka/Youtube-downloader#4]
Hi, your project Youtube-downloader(commit id: 8bfdee24b6c6cdac3cd784d8bd698523a4cd1f51) requires "pytube==11.0.1" in its dependency. After analyzing the source code, we found that the following versions of pytube can also be suitable, i.e., pytube 11.0.0, 11.0.2, 12.0.0, since all functions that you directly (2 APIs: pytube.__main__.YouTube.__init__, pytube.contrib.playlist.Playlist.__init__) or indirectly (propagate to 5 pytube's internal APIs and 4 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on pytube from "pytube==11.0.1" to "pytube>=11.0.0,<=12.0.0". This will improve the applicability of Youtube-downloader and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on pytube?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by TheHolyTachanka** [comment]
The for the suggestion I'll fix it when I get hkme, and no I don't know any automatic tool for this

**Comment by Agnes-U** [comment]
Thanks for your reply! I found that this modification has been merged before, [here](https://github.com/TheHolyTachanka/Youtube-downloader/commit/dce2038b6143866ce7976389963646722406a2d5), thanks~
